services:  
  db_service:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASS}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER:     "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASS}"
    ports:
     - "${DB_PORT}:${DB_PORT}"
    networks:
      - app-network
  backend:
    build: . 
    environment:
      PORT: "${PORT}"
      DB_HOST: db_service
      DB_PORT: "${DB_PORT}"
      DB_USER: "${DB_USER}"
      DB_PASS: "${DB_PASS}"
      DB_NAME: "${DB_NAME}"
    ports:
      - "3000:3000" 
    depends_on:
      - db_service 
    networks:
      - app-network
networks: 
  app-network:
    driver: bridge