name: Node.js CI

on: [push]
  
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        db: [mysql]

    env:
      PORT: 3000
      DB_HOST: localhost
      DB_PORT: localhost
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: storeCredits_tests
      DB_DIALECT: mysql

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: mirromutth/mysql-action@v1.1
        with:        
          character set server: 'utf8' 
          collation server: 'utf8_general_ci'         
          mysql database: 'storeCredits_test'
          mysql root password: 'test'
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}      
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test