name: Node.js CI

on: [push]
  
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        db: [mysql]

    env:
      PORT: 3000
      DB_HOST: localhost
      DB_PORT: localhost
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: storeCredits_tests
      DB_DIALECT: mysql

    steps:     
      - name: Init db ${{ env.DB_NAME }} 
      - uses: mirromutth/mysql-action@v1.1      
        with:
          character set server: 'utf8' 
          collation server: 'utf8_general_ci' 
          mysql database: ${{ env.DB_NAME }}
          mysql root password: ${{ env.DB_PASSWORD }}
          #mysql user: 'developer' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
          mysql password: ${{ env.DB_PASSWORD }} # Required if "mysql user" exists. The password for the "mysql user"
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}      
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
